<?xml version="1.0"?>
<package format="3">
  <name>global_planner</name>
  <version>1.0.0</version>
  <description>Mapeo SLAM, planificacion global con Dijkstra y suavizado B-Spline para el circuito F1TENTH del simulador AutoDRIVE.</description>
  <maintainer email="giobapena@espol.edu.ec">Giovanny Andres Bano Pena</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>

  <export><build_type>ament_python</build_type></export>
</package>
